# -*- coding: utf-8 -*-
"""
Created on Wed Jun 24 11:39:12 2020

@author: Andrew M
"""

import unittest
import golf_stat_generator

class CreateRoundsFromDataTests(unittest.TestCase):
    def setUp(self):
        self.data = [
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 1,
                "PAR": 4,
                "PUTTS": 1,
                "SCORE": 6,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 2,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 6,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "F",
                "GIR": "x",
                "HOLE": 3,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 7,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 4,
                "PAR": 3,
                "PUTTS": 1,
                "SCORE": 4,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 5,
                "PAR": 4,
                "PUTTS": 3,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "F",
                "GIR": "x",
                "HOLE": 6,
                "PAR": 4,
                "PUTTS": 1,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "-",
                "GIR": "G",
                "HOLE": 7,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 3,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 8,
                "PAR": 4,
                "PUTTS": 1,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/20/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 9,
                "PAR": 3,
                "PUTTS": 1,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "F",
                "GIR": "x",
                "HOLE": 1,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 7,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "G",
                "HOLE": 2,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 3,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "F",
                "GIR": "x",
                "HOLE": 3,
                "PAR": 4,
                "PUTTS": 1,
                "SCORE": 6,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 4,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "x",
                "GIR": "G",
                "HOLE": 5,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 4,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 6,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 6,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 7,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 8,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 9,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 4,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "F",
                "GIR": "x",
                "HOLE": 10,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 8,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 11,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 4,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 12,
                "PAR": 4,
                "PUTTS": 0,
                "SCORE": 5,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "G",
                "HOLE": 13,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 3,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "F",
                "GIR": "G",
                "HOLE": 14,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 4,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 15,
                "PAR": 4,
                "PUTTS": 3,
                "SCORE": 6,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "G",
                "HOLE": 16,
                "PAR": 3,
                "PUTTS": 2,
                "SCORE": 3,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "x",
                "GIR": "x",
                "HOLE": 17,
                "PAR": 4,
                "PUTTS": 2,
                "SCORE": 4,
            },
            {
                "COURSE": "Pleasantville CC",
                "DATE": "6/1/2020",
                "FIR": "-",
                "GIR": "x",
                "HOLE": 18,
                "PAR": 3,
                "PUTTS": 3,
                "SCORE": 6,
            },
        ]
    
    def test_normal_case(self):
        actual = golf_stat_generator.create_rounds_from_data(self.data)
        expected = [
            [
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 1,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 2,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 3,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 7,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 4,
                    "PAR": 3,
                    "PUTTS": 1,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 5,
                    "PAR": 4,
                    "PUTTS": 3,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 6,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 7,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 8,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 9,
                    "PAR": 3,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
            ],
            [
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 1,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 7,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 2,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 3,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 4,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "G",
                    "HOLE": 5,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 6,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 7,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 8,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 9,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 10,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 8,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 11,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 12,
                    "PAR": 4,
                    "PUTTS": 0,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 13,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "G",
                    "HOLE": 14,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 15,
                    "PAR": 4,
                    "PUTTS": 3,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 16,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 17,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 18,
                    "PAR": 3,
                    "PUTTS": 3,
                    "SCORE": 6,
                },
            ]
        ]
        
        self.assertListEqual(expected, actual)
        actual = golf_stat_generator.create_rounds_from_data(self.data)
        expected = [
            [
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 1,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 2,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 3,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 7,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 4,
                    "PAR": 3,
                    "PUTTS": 1,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 5,
                    "PAR": 4,
                    "PUTTS": 3,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 6,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 7,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 8,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 9,
                    "PAR": 3,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
            ],
            [
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 1,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 7,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 2,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 3,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 4,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "G",
                    "HOLE": 5,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 6,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 7,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 8,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 9,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 10,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 8,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 11,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 12,
                    "PAR": 4,
                    "PUTTS": 0,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 13,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "G",
                    "HOLE": 14,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 15,
                    "PAR": 4,
                    "PUTTS": 3,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 16,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 17,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 18,
                    "PAR": 3,
                    "PUTTS": 3,
                    "SCORE": 6,
                },
            ]
        ]
        
        self.assertListEqual(expected, actual)


class CalculateFirPercentageTests(unittest.TestCase):
    def setUp(self):
        self.data = [
            [
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 1,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 2,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 3,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 7,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 4,
                    "PAR": 3,
                    "PUTTS": 1,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 5,
                    "PAR": 4,
                    "PUTTS": 3,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 6,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 7,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 8,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/20/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 9,
                    "PAR": 3,
                    "PUTTS": 1,
                    "SCORE": 5,
                },
            ],
            [
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 1,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 7,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 2,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 3,
                    "PAR": 4,
                    "PUTTS": 1,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 4,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "G",
                    "HOLE": 5,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 6,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 7,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 8,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 9,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "x",
                    "HOLE": 10,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 8,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 11,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 12,
                    "PAR": 4,
                    "PUTTS": 0,
                    "SCORE": 5,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 13,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "F",
                    "GIR": "G",
                    "HOLE": 14,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 15,
                    "PAR": 4,
                    "PUTTS": 3,
                    "SCORE": 6,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "G",
                    "HOLE": 16,
                    "PAR": 3,
                    "PUTTS": 2,
                    "SCORE": 3,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "x",
                    "GIR": "x",
                    "HOLE": 17,
                    "PAR": 4,
                    "PUTTS": 2,
                    "SCORE": 4,
                },
                {
                    "COURSE": "Pleasantville CC",
                    "DATE": "6/1/2020",
                    "FIR": "-",
                    "GIR": "x",
                    "HOLE": 18,
                    "PAR": 3,
                    "PUTTS": 3,
                    "SCORE": 6,
                },
            ],
        ]
        
        self.rounds_to_calc = None
    
    
    def test_rounds_to_calc_none(self):
        actual = golf_stat_generator.calculate_fir_percentage(
            self.data,
            self.rounds_to_calc
        )
        expected = .6
        
        self.assertEqual(expected, actual)
    
    
    def test_rounds_to_calc_one(self):
        self.rounds_to_calc = 1
        actual = golf_stat_generator.calculate_fir_percentage(
            self.data,
            self.rounds_to_calc
        )
        expected = 1
        
        self.assertEqual(expected, actual)
    
    
if __name__ == '__main__':
    unittest.main()